./switches_fixed.sh 2sn/small_topos/linear/ryu_switches.csv 
./switches_fixed.sh 2sn/small_topos/linear/odl_switches.csv 
./switches_fixed.sh 2sn/small_topos/linear/onos_switches.csv 
./switches_fixed.sh 2sn/small_topos/datacenter/ryu_switches.csv 
./switches_fixed.sh 2sn/small_topos/datacenter/odl_switches.csv 
./switches_fixed.sh 2sn/small_topos/datacenter/onos_switches.csv 
./switches_fixed.sh 2sn/small_topos/spineleaf/onos_switches.csv 
./switches_fixed.sh 2sn/small_topos/spineleaf/odl_switches.csv 
./switches_fixed.sh 2sn/small_topos/spineleaf/ryu_switches.csv 
./switches_fixed.sh 2sn/big_topos/linear/ryu_switches.csv 
./switches_fixed.sh 2sn/big_topos/linear/odl_switches.csv 
./switches_fixed.sh 2sn/big_topos/linear/onos_switches.csv 
./switches_fixed.sh 2sn/big_topos/datacenter/onos_switches.csv 
./switches_fixed.sh 2sn/big_topos/datacenter/odl_switches.csv 
./switches_fixed.sh 2sn/big_topos/datacenter/ryu_switches.csv 
./switches_fixed.sh 2sn/big_topos/spineleaf/ryu_switches.csv 
./switches_fixed.sh 2sn/big_topos/spineleaf/odl_switches.csv 
./switches_fixed.sh 2sn/big_topos/spineleaf/onos_switches.csv 
